import {
  // 🏠 Home & Living
  Home,
  Building,
  Bed,
  Lamp,
  Key,
  Lightbulb,
  Plug,
  Leaf,
  Droplet,
  Flame,
  Cloud,
  Sun,
  Moon,
  Hammer,
  Wrench,

  // 🚗 Transport & Travel
  Car,
  Bus,
  Train,
  Ship,
  Plane,
  Bike,
  Rocket,
  Map,
  MapPin,
  Compass,
  Globe,
  Luggage,
  Ticket,
  Signpost,
  Navigation,

  // 🍔 Food & Drinks
  Utensils,
  Coffee,
  Beer,
  Wine,
  Martini,
  CupSoda,
  Pizza,
  Sandwich,
  Hamburger,
  Drumstick,
  IceCream,
  Cookie,
  Candy,
  Donut,
  ChefHat,

  // 💵 Finance & Business
  Wallet,
  PiggyBank,
  Banknote,
  CreditCard,
  DollarSign,
  Coins,
  BarChart,
  PieChart,
  LineChart,
  TrendingUp,
  TrendingDown,
  Calculator,
  Briefcase,
  Vault,
  Scale,
  Receipt,
  ClipboardList,
  FileText,
  FileCheck,
  FileSearch,
  Tag,
  Gift,
  Percent,
  Barcode,
  ShoppingBag,

  // 🎉 Entertainment & Leisure
  Music,
  Film,
  Gamepad,
  Headphones,
  Mic,
  Speaker,
  Radio,
  Tv,
  Monitor,
  Laptop,
  Smartphone,
  Tablet,
  Camera,
  Palette,
  Book,

  // 🏥 Health & Fitness
  Dumbbell,
  Stethoscope,
  Pill,
  HeartPulse,
  Syringe,
  Bandage,
  Hospital,
  Smile,
  Brain,
  Eye,
  Glasses,
  Timer,
  Cross,
  Ambulance,
  Thermometer,

  // 👔 Work & Education
  Server,
  Database,
  Printer,
  File,
  Folder,
  Ruler,
  BookOpen,
  School,
  Paperclip,
  Mail,
  IdCard,
  Calendar,
  Clock,
  AlarmClock,
  Cpu,

  // 🌳 Nature & Outdoors
  TreePine,
  TreePalm,
  Flower,
  SunMedium,
  MoonStar,
  CloudRain,
  Snowflake,
  Wind,
  Mountain,
  Binoculars,
  MapPinned,
  Footprints,
  PawPrint,
  Waves,
  FireExtinguisher,

  // 👥 Family & Personal
  Users,
  User,
  UserPlus,
  UserMinus,
  HeartHandshake,
  Diamond,
  Cake,
  Phone,
  MessageSquare,
  Bell,

  // ⚙️ Misc / System
  Settings,
  Lock,
  Shield,
  Code,
  Terminal,
  Wifi,
  QrCode,
  Upload,
  Download,
  Search,
} from "lucide-react";

export const categoryIcons = {
  // 🏠 Home & Living
  home: Home,
  building: Building,
  bed: Bed,
  lamp: Lamp,
  key: Key,
  light: Lightbulb,
  plug: Plug,
  leaf: Leaf,
  droplet: Droplet,
  flame: Flame,
  cloud: Cloud,
  sun: Sun,
  moon: Moon,
  hammer: Hammer,
  wrench: Wrench,

  // 🚗 Transport & Travel
  car: Car,
  bus: Bus,
  train: Train,
  ship: Ship,
  plane: Plane,
  bike: Bike,
  rocket: Rocket,
  map: Map,
  mapPin: MapPin,
  compass: Compass,
  globe: Globe,
  luggage: Luggage,
  ticket: Ticket,
  signpost: Signpost,
  navigation: Navigation,

  // 🍔 Food & Drinks
  food: Utensils,
  coffee: Coffee,
  beer: Beer,
  wine: Wine,
  martini: Martini,
  soda: CupSoda,
  pizza: Pizza,
  sandwich: Sandwich,
  burger: Hamburger,
  drumstick: Drumstick,
  iceCream: IceCream,
  cookie: Cookie,
  candy: Candy,
  donut: Donut,
  chefHat: ChefHat,

  // 💵 Finance & Business
  wallet: Wallet,
  savings: PiggyBank,
  cash: Banknote,
  credit: CreditCard,
  dollar: DollarSign,
  coins: Coins,
  barChart: BarChart,
  pieChart: PieChart,
  lineChart: LineChart,
  up: TrendingUp,
  down: TrendingDown,
  calc: Calculator,
  briefcase: Briefcase,
  vault: Vault,
  scale: Scale,
  receipt: Receipt,
  clipboardList: ClipboardList,
  fileText: FileText,
  fileCheck: FileCheck,
  fileSearch: FileSearch,
  tag: Tag,
  gift: Gift,
  percent: Percent,
  barcode: Barcode,
  shoppingBag: ShoppingBag,

  // 🎉 Entertainment & Leisure
  music: Music,
  film: Film,
  gaming: Gamepad,
  headphones: Headphones,
  mic: Mic,
  speaker: Speaker,
  radio: Radio,
  tv: Tv,
  monitor: Monitor,
  laptop: Laptop,
  smartphone: Smartphone,
  tablet: Tablet,
  camera: Camera,
  art: Palette,
  book: Book,

  // 🏥 Health & Fitness
  dumbbell: Dumbbell,
  stethoscope: Stethoscope,
  pill: Pill,
  heartPulse: HeartPulse,
  syringe: Syringe,
  bandage: Bandage,
  hospital: Hospital,
  smile: Smile,
  brain: Brain,
  eye: Eye,
  glasses: Glasses,
  timer: Timer,
  cross: Cross,
  ambulance: Ambulance,
  thermometer: Thermometer,

  // 👔 Work & Education
  server: Server,
  db: Database,
  printer: Printer,
  file: File,
  folder: Folder,
  ruler: Ruler,
  bookOpen: BookOpen,
  school: School,
  paperclip: Paperclip,
  mail: Mail,
  idCard: IdCard,
  calendar: Calendar,
  clock: Clock,
  alarm: AlarmClock,
  cpu: Cpu,

  // 🌳 Nature & Outdoors
  treePine: TreePine,
  treePalm: TreePalm,
  flower: Flower,
  sunMedium: SunMedium,
  moonStar: MoonStar,
  cloudRain: CloudRain,
  snowflake: Snowflake,
  wind: Wind,
  mountain: Mountain,
  binoculars: Binoculars,
  mapPinned: MapPinned,
  footprints: Footprints,
  paw: PawPrint,
  waves: Waves,
  fireExtinguisher: FireExtinguisher,

  // 👥 Family & Personal
  users: Users,
  user: User,
  userPlus: UserPlus,
  userMinus: UserMinus,
  handshake: HeartHandshake,
  diamond: Diamond,
  cake: Cake,
  phone: Phone,
  message: MessageSquare,
  bell: Bell,

  // ⚙️ Misc / System
  settings: Settings,
  lock: Lock,
  shield: Shield,
  code: Code,
  terminal: Terminal,
  wifi: Wifi,
  qr: QrCode,
  upload: Upload,
  download: Download,
  search: Search,
};
