export const qCacheKey = {
  transactions: ["transactions"],
  wallets: ["wallets"],
  categories: ["categories"],
  trashedTransactions: ["trashedTransactions"],
  currentSummary: ["currentSummary"],
  recentTransactions: ["recentTransactions"],
  topTransactions: ["topTransactions"],
  trashedWallets: ["trashedWallets"],
  trashedCategories: ["trashedCategories"],
  dailySnapshot: ["dailySnapshot"],
  topCategories: ["topCategories"],
  moneyGoal: ["moneyGoal"],
  moneyBudget: ["moneyBudget"],
};
